### ISSUE TITLE
Not launching since updating to 5.0

### ISSUE THREAD

**Issue by RasheedAZ** [flathub/io.frama.tractor.carburetor#24]
Hi. Thanks for packaging this as a flatpak. Unfortunately, it is not launching at all since the update to 5.0:

```
$ flatpak run io.frama.tractor.carburetor
Traceback (most recent call last):
  File "/app/bin/carburetor", line 46, in <module>
    from carburetor import carburetor
  File "/app/share/carburetor/carburetor/carburetor.py", line 13, in <module>
    from . import actions, ui
  File "/app/share/carburetor/carburetor/actions.py", line 19, in <module>
    from . import config, ui
  File "/app/share/carburetor/carburetor/config.py", line 18, in <module>
    countries_l10n = gettext.translation(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/gettext.py", line 528, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso3166-1'

```

**Comment by danialbehzadi** [comment]
Could not reproduce. Can you give some information about your distro?

What is the output of `locale`?

Does this fix it?

```bash
flatpak run --env=LC_ALL=en_US.UTF-8 io.frama.tractor.carburetor
```

**Comment by F-i-f** [comment]
Having the same issue on Fedora 40:
```shell
$ flatpak --user list --columns=application,version,branch,ref,active 
Application ID                               Version                  Branch      Ref                                                       Active commit
io.frama.tractor.carburetor                  5.0.0                    stable      io.frama.tractor.carburetor/x86_64/stable                 c638f10fa79a
io.frama.tractor.carburetor.pt.conjure                                stable      io.frama.tractor.carburetor.pt.conjure/x86_64/stable      c772abc48784
io.frama.tractor.carburetor.pt.lyrebird                               stable      io.frama.tractor.carburetor.pt.lyrebird/x86_64/stable     ade8d273d29c
io.frama.tractor.carburetor.pt.snowflake                              stable      io.frama.tractor.carburetor.pt.snowflake/x86_64/stable    85184010829a

$ locale
LANG=C
LC_CTYPE=en_US.utf8
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER=en_US.utf8
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

$ flatpak --user run  io.frama.tractor.carburetor
Traceback (most recent call last):
  File "/app/bin/carburetor", line 46, in <module>
    from carburetor import carburetor
  File "/app/share/carburetor/carburetor/carburetor.py", line 13, in <module>
    from . import actions, ui
  File "/app/share/carburetor/carburetor/actions.py", line 19, in <module>
    from . import config, ui
  File "/app/share/carburetor/carburetor/config.py", line 18, in <module>
    countries_l10n = gettext.translation(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/gettext.py", line 528, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso3166-1'

$ LC_ALL=C flatpak --user run io.frama.tractor.carburetor
Traceback (most recent call last):
  File "/app/bin/carburetor", line 46, in <module>
    from carburetor import carburetor
  File "/app/share/carburetor/carburetor/carburetor.py", line 13, in <module>
    from . import actions, ui
  File "/app/share/carburetor/carburetor/actions.py", line 19, in <module>
    from . import config, ui
  File "/app/share/carburetor/carburetor/config.py", line 18, in <module>
    countries_l10n = gettext.translation(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/gettext.py", line 528, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso3166-1'

$ flatpak --user run --env=LC_ALL=C io.frama.tractor.carburetor
Traceback (most recent call last):
  File "/app/bin/carburetor", line 46, in <module>
    from carburetor import carburetor
  File "/app/share/carburetor/carburetor/carburetor.py", line 13, in <module>
    from . import actions, ui
  File "/app/share/carburetor/carburetor/actions.py", line 19, in <module>
    from . import config, ui
  File "/app/share/carburetor/carburetor/config.py", line 18, in <module>
    countries_l10n = gettext.translation(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/gettext.py", line 528, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso3166-1'

$ flatpak --user run --env=LC_ALL=en_US.UTF-8 io.frama.tractor.carburetor
Traceback (most recent call last):
  File "/app/bin/carburetor", line 46, in <module>
    from carburetor import carburetor
  File "/app/share/carburetor/carburetor/carburetor.py", line 13, in <module>
    from . import actions, ui
  File "/app/share/carburetor/carburetor/actions.py", line 19, in <module>
    from . import config, ui
  File "/app/share/carburetor/carburetor/config.py", line 18, in <module>
    countries_l10n = gettext.translation(
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/gettext.py", line 528, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'iso3166-1'
```

The locale files seem to be at the wrong location:
```shell
$ flatpak --user run --env=LC_ALL=en_US.UTF-8 -d --command=/bin/strace io.frama.tractor.carburetor -ff -e file /app/bin/carburetor |& grep -i /locale/.*en_us.utf | head -n 10
openat(AT_FDCWD, "/usr/lib/locale/en_US.UTF-8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/en_US.utf8/LC_CTYPE", O_RDONLY|O_CLOEXEC) = 3
newfstatat(AT_FDCWD, "/app/share/locale/en_US.UTF-8/LC_MESSAGES/carburetor.mo", 0x7ffcf2f92700, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/share/locale/en_US.UTF-8/LC_MESSAGES/messages.mo", 0x7ffcf2f90660, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/share/locale/en_US.UTF-8/LC_MESSAGES/messages.mo", 0x7ffcf2f90660, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/share/locale/en_US.UTF-8/LC_MESSAGES/messages.mo", 0x7ffcf2f90660, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/share/locale/en_US.UTF-8/LC_MESSAGES/messages.mo", 0x7ffcf2f90660, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/en_US.UTF-8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/en_US.utf8/LC_IDENTIFICATION", O_RDONLY|O_CLOEXEC) = 4
openat(AT_FDCWD, "/usr/lib/locale/en_US.UTF-8/LC_MEASUREMENT", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
The SDK locale files in `/usr/lib/locale/_localeName_/_localeCategory_/_localeFile_` are found.
Carburetor looks for its messages files in in `/app/share/locale/_localeName_/_localeCategory_/_localeFile_`.
But these are missing and only the `/app/share/locale/_localeName_` directories are present. The locale files themselves are in `/app/share/runtime/locale`:
```shell
$ flatpak --user run --env=LC_ALL=en_US.UTF-8 -d --command=/bin/find io.frama.tractor.carburetor /app | grep -i /locale/.*fr   
/app/share/locale/fr
/app/share/runtime/locale/fr
/app/share/runtime/locale/fr/share
/app/share/runtime/locale/fr/share/fr
/app/share/runtime/locale/fr/share/fr/LC_MESSAGES
/app/share/runtime/locale/fr/share/fr/LC_MESSAGES/carburetor.mo
```

**Comment by danialbehzadi** [comment]
I made a blind patch for this:
https://github.com/flathub/io.frama.tractor.carburetor/pull/25

It's still weird for me since flatpaks are intended to run as same everywhere.

**Comment by RasheedAZ** [comment]
> Could not reproduce. Can you give some information about your distro?
> 
> What is the output of `locale`?
> 
> Does this fix it?
> 
> ```shell
> flatpak run --env=LC_ALL=en_US.UTF-8 io.frama.tractor.carburetor
> ```

Sorry should have included this. Distro: postmarketOS 24.06  `locale: not found`

It launches now after the update. Has never worked though : ) Neither the flatpak, nor the native apk package. I'll open issue for that on Framagit.

**Comment by mokazemi** [comment]
> I made a blind patch for this: #25
> 
> It's still weird for me since flatpaks are intended to run as same everywhere.

I had the same issue yesterday but just updated right now (probably after getting the patch) and now it's working correctly. ✅
